### ISSUE TITLE
Redesign required

### ISSUE THREAD

**Issue by maziac** [maziac/asm-code-lens#1]
I should keep all CodeLenses alive in arrays to determine which require an update.
vscode 1.27 provides a new search API:
workspace.findTextInFiles

See thread here:
https://vscode-dev-community.slack.com/messages/C74CB59NE/convo/C74CB59NE-1535575944.000100/

I.e.:
I'm trying to implement one but it's really hard to find any good documentation.
On first glance everything looks straightforward, but when it comes to more complicated use cases I have no idea how it should work.
Basically the CodeLensProvider has an interface like this:

provideCodeLenses: called initially or on every edit.
resolveCodeLens: Delayed resolve of the CodeLens.
onDidChangeCodeLenses: Inform vscode that code lenses have changed. vscode will call provideCodeLenses.

The CodeLens extension should be for assembler files. So like in other programming languages I would like to provide
a code lens for each label. The code lens title string will contain the number of references. Those references are
basically grepped from the other files in the workspace from disk.

I.e. in order to provide information if the references changed I would need to register for all filesystem events.
And re-grep the changed file for that code lens. Then if a code lens would change I would need to inform
vscode about it so it can update the code lens but
(1rst question) is there any API for this? I can only notify a change on ALL lenses(onDidChangeCodeLenses),
i.e. all lenses are calculated again because provideCodeLenses is called which results in a complete re-grep of all references.
Seems to result in a lot of computation time .

2nd question: I cannot read all files from the disk because some are opened in the editor and some might be even unsaved (dirty) in the editor.
Is there any API in vscode that allows grepping transparently, i.e. that it does not matter if the file is opened in vscode or just lying around on the disk?

3rd question: If there is no such API is there any way to tell which files are opened in vscode? The workspace.textDocuments array just returns all
documents, no way to tell which one is open.

Answer:
1. **CodeLens change API**: Unfortunately not, you can only signal that there are changes which will call `provideCodeLenses`
2. **Transparently grepping**: Not currently but there is a proposed api for it here: https://github.com/Microsoft/vscode/issues/9049 (hopefully it will land in the August release)
3. **Open documents**: Sadly there is no good api to tell you if a document is open -- although if a document is in `workspace.textDocuments` it is either open or was recently opened

**Comment by mjmatthiesen** [comment]
Hey! Sorry for this weird unrelated comment, but I'm exploring vs code extensions right now, and am struggling a bit with certain aspects of the API, so I've been reading the code of other projects. Yours might be the most clear I've come across so far honestly.

I saw the link to a slack - is this something public that anyone could potentially join?

**Comment by maziac** [comment]
Thanks :-)
Yes, that vscode-dev-community slack is publicly available.
AFAIR you just have to register.

**Comment by mjmatthiesen** [comment]
Great. Thanks! It says I need to contact the workgroup admin, but it doesn't have any information as to who that is. I don't use slack, so maybe I am missing something.

You can also email me if you prefer to keep your repo cleaner.

Dein Projekt hat mir jetzt schon ziemlich viel geholfen. Danke!

**Comment by maziac** [comment]
> Am 15.01.2019 um 23:13 schrieb mjmatthiesen <notifications@github.com>:
> 
> Great. Thanks! It says I need to contact the workgroup admin, but it doesn't have any information as to who that is. I don't use slack, so maybe I am missing something.
> 
> You can also email me if you prefer to keep your repo cleaner.
> 
> Dein Projekt hat mir jetzt schon ziemlich viel geholfen. Danke!
> 
Das freut mich.

Ich erinnere mich, dass ich ähnliche Probleme hatte die Registrierung zu finden.
Probier mal den Link hier:
https://vscode-dev-community.slack.com/join/shared_invite/enQtMjIxOTgxNDE3NzM0LWU5M2ZiZDU1YjBlMzdlZjA2YjBjYzRhYTM5NTgzMTAxMjdiNWU0ZmQzYWI3MWU5N2Q1YjBiYmQ4MzY0NDE1MzY <https://vscode-dev-community.slack.com/join/shared_invite/enQtMjIxOTgxNDE3NzM0LWU5M2ZiZDU1YjBlMzdlZjA2YjBjYzRhYTM5NTgzMTAxMjdiNWU0ZmQzYWI3MWU5N2Q1YjBiYmQ4MzY0NDE1MzY>

Sonst weiß ich auch nicht.

**Comment by mjmatthiesen** [comment]
Danke für die Hilfe. Bin jetzt erst mal mit meiner Extension fertig.
