### ISSUE TITLE
execution time information is not displayed

### ISSUE THREAD

**Issue by DeadlyKom** [maziac/asm-code-lens#101]
![image](https://github.com/maziac/asm-code-lens/assets/23453697/fd225c07-dbc0-40e9-be3b-06c3c705a7ee)

**Comment by maziac** [comment]
I guess you are referring to a display in the status bar  like this:
![Bildschirmfoto 2023-10-21 um 11 44 59](https://github.com/maziac/asm-code-lens/assets/3081973/04a9fa83-2234-4400-8cc4-1e8f94790bd5)

That actually is not Asm-Code-Lens but 
![Bildschirmfoto 2023-10-21 um 11 45 48](https://github.com/maziac/asm-code-lens/assets/3081973/b1d43323-857c-4c48-a8e6-75cef17f5117)

**Comment by DeadlyKom** [comment]
those. you suggest me not to use Asm-Code-Lens?

**Comment by maziac** [comment]
:-) 
Asm-Code-lens is doing a lot of stuff, but it is not calculating execution times.
This functionality is not implemented.

If you want this functionality you need to install another extension.

I don´t understand why you think that asm-code-lens would calculate execution times.
