### ISSUE TITLE
M80 supports $ inside labels.

### ISSUE THREAD

**Issue by ravn** [maziac/asm-code-lens#103]
I have some ancient code written by me, which was assembled with M80.   Apparently I found out that M80 supports $-signs in labels as I have code looking like:

----
	iff	LS$ena		; Hvis ikke defineret, så returner true
	 ld	a, true
	 ret
	else			; ellers udfør oprindelig kode
	
	ADD	A, T$Ctrl	; 
	LD	C,A		; 
----

ASM Code Lens recognizes the individual identifiers T and Ctrl, not T$Ctrl.

**Comment by ravn** [comment]
I would be fine with you making the regexp recognizing an identifier configurable, so I can just fix it myself.  Slap big red warnings on it saying "only change this if you know what you are doing"-stuff.

**Comment by maziac** [comment]
Actually this will result in hard to find misbehavior.

I would propose that you fork the project and change it for your needs.

Here are the functions to change in src/regexes/commonregexes.ts:

~~~js

    /**
     * Returns labels with and without a colon.
     * Not to be used for list files.
     * Capture groups:
     *  1 = '@' or ''
     *  2 = the label itself e.g. "init.label_1"
     */
    public static regexLabelWithAndWithoutColon(): RegExp {
        return /(^@?)([a-z_][\w.]*):?/i;
    }


    /**
     * Checks for a label with a colon, e.g.
     * "label:", " label:" or "init.label_1:".
     * Also "@label:".
     * But not ".label:".
     * Capture groups:
     *  1 = preceding spaces (and other chars in case of list file) otherwise '@' or ''
     *  2 = the label itself e.g. "init.label_1
     * Used by findLabelsWithNoReference, provideCodeLenses.
	 * @param languageId either "asm-collection" or "asm-list-file".
	 * A different regex is returned dependent on languageId.
     */
    public static regexLabelWithColon(languageId: AllowedLanguageIds): RegExp {
        if (languageId === 'asm-list-file') {
            return new RegexIndexOf(':', /(^[^#]*\s@?)([a-z_][\w.]*):/i);
        }
		// "asm-collection"
        return /(^@?)([a-z_][\w.]*):/i;
    }


    /**
     * Checks for a label without a colon, i.e. a
     * label used by sjasmplus.
     * E.g. "label" or "init.label_1".
     * Also "@label".
     * But not ".label".
     * Capture groups:
     *  1 = '@' or ''
     *  2 = the label itself e.g. "init.label_1"
     * Used by findLabelsWithNoReference, provideCodeLenses.
     */
    public static regexLabelWithoutColon(): RegExp {
        return /^(@?)([a-z_][\w.]*)(?:\s|$)/i;
    }
~~~

I.e. 3 regular expressions to change, one for labels without colons, one for labels ending with a colon (":") and one which checks for both options.
