### ISSUE TITLE
Colour of push/pop highlighting

### ISSUE THREAD

**Issue by lkct** [maziac/asm-code-lens#107]
Hi, thank you for the amazing project!

I would like to suggest an enhancement of the push/pop matching and highlighting. As in the screenshot below, when there are a lot of push instructions (same for pop), some will be coloured blue (e.g. `push r13` below), which is not really a "highlight" because it's too close to the colour of other instructions (e.g. mov below). Can you please update the colours so that push/pop does stand out? Thanks again!

![image](https://github.com/user-attachments/assets/e7092238-6462-463a-993b-8db928bf490d)

**Comment by maziac** [comment]
AFAIR the colorization comes from vscode. 
The push/pop uses the bracket colorization.
I think you can customize it in the cmd palette. Please google for "Bracket Pair Colorization".

**Comment by lkct** [comment]
Thanks for the reply. It's indeed controlled by the bracket colours.
