### ISSUE TITLE
About this plug-in

### ISSUE THREAD

**Issue by lzyq0912** [maziac/asm-code-lens#14]
Hello ,i am  a student from china
When I used your plugin,I found that it just can make my code highlight,but it can't complete my code automatically.

**Comment by maziac** [comment]
This can have various reasons.
First: your file extension must be one of .{asm,inc,s,a80}.
You can change that in the settings (Include-Files).

Second: Code completion works for labels.
I.e. your code must contain labels (something like "label:").
asm-code-lens will grab those labels and offer them for completion.

Maybe you can attach your code here to see what th problem is.

**Comment by lzyq0912** [comment]
Thank you very much .In fact ,I just want it to finish some easy code . For example ,I want it to complete the ()，‘’，“”；but I can't lmplement these features.You can take a look at my attachments.




------------------ 原始邮件 ------------------
发件人: "maziac"<notifications@github.com>;
发送时间: 2019年10月4日(星期五) 凌晨5:00
收件人: "maziac/asm-code-lens"<asm-code-lens@noreply.github.com>;
抄送: "白夜"<1197795731@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [maziac/asm-code-lens] About this plug-in (#14)




This can have various reasons.
 First: your file extension must be one of .{asm,inc,s,a80}.
 You can change that in the settings (Include-Files).
 
Second: Code completion works for labels.
 I.e. your code must contain labels (something like "label:").
 asm-code-lens will grab those labels and offer them for completion.
 
Maybe you can attach your code here to see what th problem is.

**Comment by lzyq0912** [comment]
------------------ 原始邮件 ------------------
发件人: "maziac"<notifications@github.com>;
发送时间: 2019年10月4日(星期五) 凌晨5:00
收件人: "maziac/asm-code-lens"<asm-code-lens@noreply.github.com>;
抄送: "兰秋仲阳"<1197795731@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [maziac/asm-code-lens] About this plug-in (#14)




This can have various reasons.
 First: your file extension must be one of .{asm,inc,s,a80}.
 You can change that in the settings (Include-Files).
 
Second: Code completion works for labels.
 I.e. your code must contain labels (something like "label:").
 asm-code-lens will grab those labels and offer them for completion.
 
Maybe you can attach your code here to see what th problem is.

**Comment by maziac** [comment]
I couldn't find any attachment.
However, asm-code-lens will not complete brackets or similar.
It is for assembler code.

E.g. if you have:
~~~
   ld a,8
mylabel:
  jr z,nextlabel
  ld a,7
nextlabel:
 dec a
~~~
and you type e.g.
~~~
  jr myl 
~~~
It will offer completion "mylabel".

**Comment by lzyq0912** [comment]
No No No, you don't realize what I mean,I just want it to compete some special symbol like (),'',"",[],{}.I think your asm-code-lens is the best plugin when I write assembly file.So can I take the liberty to ask a question?Are you able to remotely control my computer to detect problems when we are both awake?




------------------ 原始邮件 ------------------
发件人: "maziac"<notifications@github.com>;
发送时间: 2019年10月5日(星期六) 凌晨3:58
收件人: "maziac/asm-code-lens"<asm-code-lens@noreply.github.com>;
抄送: "兰秋仲阳"<1197795731@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [maziac/asm-code-lens] About this plug-in (#14)




I couldn't find any attachment.
 However, asm-code-lens will not complete brackets or similar.
 It is for assembler code.
 
E.g. if you have:
    ld a,8 mylabel:   jr z,nextlabel   ld a,7 nextlabel:  dec a  
and you type e.g.
   jr myl   
It will offer completion "mylabel".

**Comment by maziac** [comment]
Ok, I’m located in germany. I could offer you tomorrow 6.10. 12:00 MESZ if that‘s ok to you.
I guess we would use teamviewer to connect?
Could you post your email address, so I can contact you.

**Comment by lzyq0912** [comment]
Thank you very much.However ,I am asleep at that time .But I have already find the prolem by myself. I think your plgin is very good. Thank you very much. i am sorry about that I have delayed your time. By the way , I hope we can contact with each other since then. If I have another problem about my study , could I ask you for some questions? It is my pleasure to become your friend. I am really grateful to accept your help. Below is the way to contact to me. 
My email address: 1197795731@qq.com
Because some political reasons. I can not contact with you through instant messaging tools. I am sorry about that.------------------ 原始邮件 ------------------
发件人: "maziac"<notifications@github.com>;
发送时间: 2019年10月5日(星期六) 晚上10:29
收件人: "maziac/asm-code-lens"<asm-code-lens@noreply.github.com>;
抄送: "兰秋仲阳"<1197795731@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [maziac/asm-code-lens] About this plug-in (#14)




Ok, I’m located in germany. I could offer you tomorrow 6.10. 12:00 MESZ if that‘s ok to you.
 I guess we would use teamviewer to connect?
 Could you post your email address, so I can contact you.

**Comment by maziac** [comment]
Great to hear that you could solve the issue.
What is this other problem you are talking about?
