### ISSUE TITLE
Question about using this plugin with Kate editor (or other LSP-enabled editors)

### ISSUE THREAD

**Issue by ped7g** [maziac/asm-code-lens#19]
I read there's incoming support of LSP into Kate editor ( https://kate-editor.org/post/2020/2020-01-01-kate-lsp-client-status/ )

Forgive me my ignorance, I haven't used VSC ever and I'm confused by the whole ecosystem, spent minimum amount of time familiarizing with how it works and what is what, so I have probably kinda dumb question...

Is asm-code-lens LSP server? If yes, any idea how to install it without VSC to make it available to kate? What technology does it use to run, something like node.js, or it's "server/client" from the architecture point of view, but the client editor is running the infrastructure, etc?

By a chance, do you have some idea where I should look and what to study to understand these things better? Thanks.

**Comment by maziac** [comment]
For me I don't know LSP at all :-)
But I doubt that you can use asm-code-lens with it. Of course, you could take the code and make it to work with LSP, but I don't know how difficult it is.

asm-code-lens is written in TypeScript and uses node-js. It communicates via an extension API that vscode provides.
See https://code.visualstudio.com/api/references/vscode-api, e.g. registerCompletionItemProvider.

vscode is definitely worth a try. I accidentally found it myself but was positively surprised especially by its extensibility. I used emacs in the past and had the feeling that the concept was quite similar:
vscode is "just" an editor but provides interfaces. And then you have this massive ecosystem with extensions that you can install just with a few clicks.
And, after all, it is cross platform.
