### ISSUE TITLE
Code lens does not work.

### ISSUE THREAD

**Issue by LightMelodies** [maziac/asm-code-lens#23]
The import statement in extension.ts line 7 `import { CodeLensProvider } from './CodeLensProvider';` uses upper case 'L' while the source file use a lower case 'l', which result in **Error: Cannot find module './CodeLensProvider'** in case insensitive system such as linux. Change it to `import { CodeLensProvider } from './CodelensProvider';` will fix it.

**Comment by maziac** [comment]
Thanks for reporting.
In my workspace the file was CodeLensProvider.ts for a long time, but the change was not reflected in git.
Corrected now in 1.4.3.
