### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Jerri1977** [maziac/asm-code-lens#25]
- Issue Type: `Bug`
- Extension Name: `asm-code-lens`
- Extension Version: `1.4.3`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 48,
		"activateCallTime": 1,
		"activateResolvedTime": 7,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "maziac.asm-code-lens",
				"_lower": "maziac.asm-code-lens"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by maziac** [comment]
?
What actually is the bug?

**Comment by maziac** [comment]
I have no idea what you meant. So I‘m closing this one. If you still have a problem please explain in more detail.
