### ISSUE TITLE
RFE: Populate Outline View

### ISSUE THREAD

**Issue by bryceschober** [maziac/asm-code-lens#26]
It sure would be nice to populate the outline view, even if it is only a non-hierarchical view of all the labels in the current file.

**Comment by maziac** [comment]
Sounds interesting. I will think about it.

**Comment by maziac** [comment]
I implemented an outline view feature.
Could you install the following file manually in vscode (F1 command palette "Install vsix..."):
[asm-code-lens-1.4.6.vsix.zip](https://github.com/maziac/asm-code-lens/files/4611185/asm-code-lens-1.4.6.vsix.zip)
and tell me if it works for you.

**Comment by bryceschober** [comment]
Looks good, thanks!
