### ISSUE TITLE
local labels not recognized properly?

### ISSUE THREAD

**Issue by illbebach** [maziac/asm-code-lens#34]
hover over local labels (that start with period) not working.  Possibly related to issue #30 

Outlining appears OK, just the display and hover.

When I right-click over .loop9 and select `Go to Reference`, I get a message saying `no definition found for 'loop9'`

![image](https://user-images.githubusercontent.com/1385858/83049606-11b23000-a011-11ea-9e3b-e3b8ab59dbb2.png)

![image](https://user-images.githubusercontent.com/1385858/83049952-6a81c880-a011-11ea-9f4a-b598e71d40ab.png)

**Comment by maziac** [comment]
Yes, this is most probably related to #30.
