### ISSUE TITLE
ARM assembly

### ISSUE THREAD

**Issue by Trass3r** [maziac/asm-code-lens#42]
Does this support ARM assembly too?

**Comment by maziac** [comment]
At the moment it supports Z80 and Intel.
But try it, many mnemonics are the same for syntax highlighting.

But apart of the syntax highlighting the recognition of labels and navigation should work many independent the syntax.
To recognize labels a label need to start a line and/or end with a ":"
Recognized file extensions are: .list .lis .a80 .asm .inc .s

If you like you can extend it and provide a pull request.
