### ISSUE TITLE
support for combined listings

### ISSUE THREAD

**Issue by Trass3r** [maziac/asm-code-lens#43]
With address and/or the bytes as produced by `objdump` or debuggers maybe https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#disassembly-view.
Probably out of scope but fwiw.

**Comment by maziac** [comment]
A guess you are talking about the syntax highlighting or what of the actual features you want to us in this view.

**Comment by Trass3r** [comment]
I guess for debuggers mainly highlighting and maybe jumping to address "labels": `je     0x7fffff3c579d`.
For an objdump or https://github.com/Trass3r/cxx-compiler-explorer disassembly all features that make sense.

**Comment by maziac** [comment]
I guess this is out of scope.
