### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nodpc** [maziac/asm-code-lens#51]
- Issue Type: `Performance`
- Extension Name: `asm-code-lens`
- Extension Version: `1.5.8`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\MAKSIM~1\AppData\Local\Temp\maziac.asm-code-lens-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by maziac** [comment]
Thanks for your report.
Could you please attach your 
c:\Users\MAKSIM~1\AppData\Local\Temp\maziac.asm-code-lens-unresponsive.cpuprofile
file.

**Comment by maziac** [comment]
Do you still have problems?
If so, please attach the profile file.

**Comment by maziac** [comment]
Closed because of missing input.
