### ISSUE TITLE
"./whatsnew/whatsnewview.ts" seems to rename to "./whatsnew/WhatsNewView.js"

### ISSUE THREAD

**Issue by chribjel** [maziac/asm-code-lens#52]
When i installed the extension (also tried to reinstall), the extension wouldn't start. I opened developer tools, and it seems like in the "extension.js file you try to require "./whatsnew/whatsnewview", but the file is named using CameCase. Possibly because of the class name?

System: Windows 10 build 19042.685 using WSL Ubuntu 20.10.
VS code: 1.52.1

**Comment by maziac** [comment]
Hmm,
CamelCasing shouldn't be a problem on Windows.

I just tried to install on Windows and on Mac. Both seem to work fine.
Which asm-code-lens version are you referring to?

**Comment by chribjel** [comment]
This happened on extension v1.6.3 on WSL on Windows. It should in practice be the same as Ubuntu 20.10. I went into the actual extension files and renamed the filename to lowercase and it resolved the problem. On Windows it seems to run fine!

I find it interesting that the file renames to CamelCase though? Seems like a weird typescript quirk.

**Comment by maziac** [comment]
Strange that this does not happen on mac though.

**Comment by maziac** [comment]
What file do you actually rename? I looked into the extension and there are actually to CamelCase WhatsNewView.js:
out/src/WhatsNewView.js and
out/src/whatsnew/WhatsNewView.js and

**Comment by maziac** [comment]
OK, I see the problem now. 
Originally the file was camel case. And I once compiled it (CamelCase). Then it was stored to the out directory in CamelCase.
Later I renamed to lowercase and compiled again.
The file contents of the CamelCase file was replaced but the name remained CamelCase.
I now removed the out directory and compiled once again. Now everything should be fine.
Could you try the version 1.6.4 here:
https://github.com/maziac/asm-code-lens/tree/master/releases

**Comment by chribjel** [comment]
This now works as expected. Nice job! Thanks for the fast response

**Comment by maziac** [comment]
Thanks very much for finding and reporting.

**Comment by reporter123** [comment]
Yeah linux file systems are case sensitive by default that's the underlying cause. Windows and MacOS merely preserve case.
