### ISSUE TITLE
Line comment highlighting

### ISSUE THREAD

**Issue by ammehet** [maziac/asm-code-lens#54]
Looks like in version 1.7.0 the # symbol is highlighted as a comment
![image](https://user-images.githubusercontent.com/47472465/107049744-87df7700-67db-11eb-8349-948153d87365.png)

In 1.6.4 everything looks great
![image](https://user-images.githubusercontent.com/47472465/107049426-20292c00-67db-11eb-9196-3720d48614d5.png)

**Comment by maziac** [comment]
Yes, right. I added PR from chribjel to allow '#' as well for commenting.
This seems to be allowed in "AT&T syntax for i386".

Your snippets, what assembler is this?

**Comment by maziac** [comment]
Seems that sjasmplus is also using # for hex numbers.

**Comment by maziac** [comment]
Fixed in 1.7.1
