### ISSUE TITLE
Small issue with reference count of labels

### ISSUE THREAD

**Issue by SBelleguelle** [maziac/asm-code-lens#69]
Hi Maziac,

  Thanks for putting such effort into the ASM Code Lens plugin.  I'm just testing it out and I noticed a small issue with it.

 I am using the following simple code.

      ; ROM routines
      ROM_CLS     equ $0DAF
      ROM_PRINT   equ $203C
      
      ; Character Codes
      ENTER       equ $0D
      
      
      hello:
         db "Hello, World!", ENTER
      HELLO_LEN   equ $ - hello
      
      print_hello:
         call ROM_CLS
         ld de,hello
         ld bc,HELLO_LEN
         call ROM_PRINT
         ret

In the attached screenshot, you'll see the ENTER label is used but the reference count is 0.

If I split the db into 2 lines, it works.
```
         db "Hello, World!"
         db ENTER

```
I've found the same behaviour with dw.

If, however, I have
`         db ROM_PRINT, ENTER`
it works okay.  It seems that it's the use of a label after text.

![ASM Code Lens - Reference Counting](https://user-images.githubusercontent.com/49337375/159477434-17f5580c-46fa-4f47-81c5-a2fd148aae6b.png)
 
Best wishes,
  Steve

**Comment by maziac** [comment]
Thanks for posting.
This is truly an error.
Actually I looked at  the regex: I'm disregarding anything after the first parenthesis.
That's why it does not appear.
Let me see what I can do.

**Comment by maziac** [comment]
I have a fix. Was more difficult than expected.
Please try:
[asm-code-lens-1.9.2-rc1.vsix.zip](https://github.com/maziac/asm-code-lens/files/8336247/asm-code-lens-1.9.2-rc1.vsix.zip)

For the multiline comments I will add a feature request. Not sure yet if that can be doe easily.
I guess this is for "/* ... */" or are you thinking of any other pattern.

**Comment by SBelleguelle** [comment]
That seems to have done the job - thank you for your efforts. :-)  

Yes, I was thinking of the /* ... */ pattern and expect it would be somewhat more complex to include.

**Comment by maziac** [comment]
Hello SBelleguelle,
If have first version for multiline comments.
You can try it here: 
https://github.com/maziac/asm-code-lens/issues/70

**Comment by SBelleguelle** [comment]
Hi Maziac,

 

Sorry for the delay.  I’ve just given the new code a quick test and it seems to be working as expected – good work 😊

 

Thank you

**Comment by SBelleguelle** [comment]
Hi Maziac,

 

I’ll have a look as soon as I get a chance.

 

Thank you,

  Steve
