### ISSUE TITLE
should have info message instead of error message in donation info

### ISSUE THREAD

**Issue by wawan-ikhwan** [maziac/asm-code-lens#74]
I think it's not right icon in donation info, my eyes sensitive with  :x:. It will better if the icon is  :information_source:

![image](https://user-images.githubusercontent.com/72451078/178135142-c60a178c-6e0d-4f19-9dd5-24338d7a03c4.png)

**Comment by maziac** [comment]
Don't worry. The message will be gone after 2 weeks or if you set the 'donated' variable in the settings.

I will anyhow drop the implementation in the next release:
There was only 1 donation in 70000 users.
So, it's not worth the effort.

**Comment by maziac** [comment]
Fixed in asm-code-lens 2.0.
(Additionally donation hint is disabled in 2.0.0)
