### ISSUE TITLE
Incorrect search for definitions

### ISSUE THREAD

**Issue by Tolik-Trek** [maziac/asm-code-lens#80]
When the label is located immediately after the comment, then this label is not defined.

Before:
<img width="270" alt="Before" src="https://user-images.githubusercontent.com/85737314/203256304-412126fb-2394-4f7f-ad06-ad0c19a0cb0e.png">

After:
<img width="219" alt="After" src="https://user-images.githubusercontent.com/85737314/203256353-123f299f-ba0e-4af3-9786-9bbbba9767af.png">

Hm.... not so easy... After editing everything calculates correctly, and after saving it is wrong again

<img width="985" alt="image" src="https://user-images.githubusercontent.com/85737314/203259771-c5efd698-9c8b-400f-8349-f0ba5d7b30a0.png">

Hm... not so easy again... comments and editing is not the cause...

**Comment by maziac** [comment]
I couldn't reproduce this yet.
It could also be related to other files in your project.
Could you maybe add your zipped project here?

**Comment by Tolik-Trek** [comment]
> I couldn't reproduce this yet.

I renamed the project folder, then gave it the old name and the bug with changing the number of references disappeared. Now it just displays zero references, although there are uses of these labels in other project files.

> It could also be related to other files in your project.

Or some magic)))

> Could you maybe add your zipped project here?

Yes, but not all files.  File MAIN.asm -> label DOUBLE and some other near it. In file settings.asm there is CALL DOUBLE. 
"asm-code-lens.enableFindAllReferences": true

[Bug_Test.zip](https://github.com/maziac/asm-code-lens/files/10074878/Bug_Test.zip)

**Comment by maziac** [comment]
Could you please check if it works with the new 2.0.1 release.
https://github.com/maziac/asm-code-lens/releases/tag/v2.0.1
(or from market place)

**Comment by Tolik-Trek** [comment]
> Could you please check if it works with the new 2.0.1 release.
> https://github.com/maziac/asm-code-lens/releases/tag/v2.0.1
> (or from market place)

Perfect! It's workштп! Thanks a lot! 
Another question about hovering labels. It is not work in Bug_Test project on label, for example, SDOUBLE. Was that how it was intended? I think it would be more convenient to display them anyway on hover.

**Comment by maziac** [comment]
I will have a look.
But give me a few days.

**Comment by Tolik-Trek** [comment]
> I will have a look.
Need a new Issue?
> But give me a few days.

**Comment by maziac** [comment]
Yes, proably.
But, doesn't matter.

**Comment by maziac** [comment]
I tested this now, but what exactly is the issue? Hovering is working for me. With single line comments and with multiline.

Important is that 
a) the comment directly starts above the label. I.e. no newline is allowed in between.
b) the file with the label/comment need to be saved to disc. I.e. if the comment has just been entered without saving the file it will not appear.

**Comment by Tolik-Trek** [comment]
> I tested this now, but what exactly is the issue? Hovering is working for me. With single line comments and with multiline.

OK. I thought there is a different logic, like in the z80 Macro-Assembler, where the hover shows several lines above the label and several lines below it.

Another issue, please forgive me)))
The files in my projects are in the CP866 code page. But on hover, they were displayed in UTF-8. Is it possible to set the default hover code page? Or the first line in the file could be a code page comment for that file, like so:
;CP866
