### ISSUE TITLE
Another codepages

### ISSUE THREAD

**Issue by Tolik-Trek** [maziac/asm-code-lens#82]
Hi!
The files in my projects are in the CP866 code page. But on hover, they were displayed in UTF-8. Is it possible to set the default hover code page? Or the first line in the file could be a code page comment for that file, like so:
;CP866

**Comment by maziac** [comment]
Couldn't you simply format your code in utf-8?
(Actually I would like not to mess around with codepages anymore these days)

BTW if I display the file with CP866 in vscode it looks like this:
![Bildschirmfoto 2022-11-29 um 18 22 23](https://user-images.githubusercontent.com/3081973/204598743-f2cab88c-498a-42aa-b8f4-fb4cbd8aead1.jpg)
I.e. this does not look right either.

**Comment by Tolik-Trek** [comment]
> Couldn't you simply format your code in utf-8? (Actually I would like not to mess around with codepages anymore these days)
> 
> BTW if I display the file with CP866 in vscode it looks like this:

there is no way to use UTF-8 yet. I do not insist on a fix, but you can try to take the code from the z80 Macro-Asm, there are no problems with the encoding. As an option - display hovers in the encoding selected for the current open file.
And this is how it looks for me:
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/85737314/204851932-4bc0e81d-bec6-49d2-9821-b02d380728a2.png">

**Comment by maziac** [comment]
OK, I'll have a look.
But strange is that even vscode shows wrong characters even if I choose CP 866.

**Comment by Tolik-Trek** [comment]
> OK, I'll have a look. But strange is that even vscode shows wrong characters even if I choose CP 866.

maybe you don't have Russian fonts in your OS?

**Comment by maziac** [comment]
And here is hopefully a fix for the codepage.
Not sure if it works as on my mac the codepage is anyhow not correctly drawn.
[asm-code-lens-2.0.2-rc2.vsix.zip](https://github.com/maziac/asm-code-lens/files/10134933/asm-code-lens-2.0.2-rc2.vsix.zip)

**Comment by Tolik-Trek** [comment]
> And here is hopefully a fix for the codepage.
> Not sure if it works as on my mac the codepage is anyhow not correctly drawn.
> [asm-code-lens-2.0.2-rc2.vsix.zip](https://github.com/maziac/asm-code-lens/files/10134933/asm-code-lens-2.0.2-rc2.vsix.zip)

Perfect! Thanks a lot)))
