### ISSUE TITLE
Incomplete comment marks as comment the next line

### ISSUE THREAD

**Issue by luc0x61** [maziac/asm-code-lens#87]
I'm verifying some generated ASM by MinGW/GCC and the assembly code has sometimes an empty end-of-line comment, using '#' as follows:
```
	push	edi	 #
	push	esi	 #
	push	ebx	 #
	sub	esp, 112	 #,
```
In the above case, the second and the fourth line are color-marked as **comments**.
It's sufficient to have any character following the '#' and the following line is fine. Lines here are CR/LF terminated.
Note that EOL comments with ';' don't show this behavior. As this is automatically generated by GCC (with -masm=intel) I can't change the EOL comment style.

**Comment by maziac** [comment]
Thanks for reporting.
Could you please unzip and install the following version:
[asm-code-lens-2.1.1-rc1.vsix.zip](https://github.com/maziac/asm-code-lens/files/10230128/asm-code-lens-2.1.1-rc1.vsix.zip)

I changed the order of pattern recognition, hopefully it does not break other highlighting.

**Comment by luc0x61** [comment]
@maziac Perfect, that fixed it, thanks!
