### ISSUE TITLE
highlighted files in the explorer

### ISSUE THREAD

**Issue by DeadlyKom** [maziac/asm-code-lens#88]
the problem of updating highlighted files in the explorer after fixing them (continues to highlight them). restart helps.

https://github.com/microsoft/vscode/issues/169049

**Comment by maziac** [comment]
Which version of asm-code-lens are you using.
Can you put your tasks.json here.
I guess you are using asm-code-lens' problem-matcher: $problem-matcher-sjasmplus or anything else?

**Comment by DeadlyKom** [comment]
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "sjasmplus",
            "type": "shell",
            "command": "./Build/SPG/Build.bat",
            "problemMatcher": {
                "owner": "c",       //-> added this and seems to have solved the problem
                "fileLocation": [
                    "relative",
                    "${workspaceRoot}"
                ],
                "pattern": {
                    "regexp": "^(.*)\\((\\d+)\\):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 3,
                    "message": 4
                }
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
