### ISSUE TITLE
Use a bundler and exclude node_modules

### ISSUE THREAD

**Issue by Crystal-RainSlide** [maziac/asm-code-lens#89]
This extension only has a handful of dependencies, but packs a node_modules folder with 67.4 MB and 2356 files.
A bundler can pack the nessary part of those dependencies only, and bundle everything into 1 smaller js file.
See https://code.visualstudio.com/api/working-with-extensions/bundling-extension . Remember to set the `main` key in the `package.json` if you modified the output (entry js file location for the ext.).

Also, `assets/codelens_usage.gif` can be excluded in `.vscodeignore`.

I can do a PR on those if you'd like it.

**Comment by maziac** [comment]
I tried this once (in another extension) a few years ago but the packed extension was not working properly afterwards, so I reverted.
But maybe I made some mistake or it was simply too early that time.

So, yes, if you could do that, please provide a PR.

**Comment by maziac** [comment]
I'm struggling with debugging using esbuild.
It does not stop on breakpoints although the extension.js and the extension.js.map are created in the out dir.
Can you help?

**Comment by Crystal-RainSlide** [comment]
Will look into it.

**Comment by Crystal-RainSlide** [comment]
I got no problem with breakpoints.

![Screenshot of VSCode debugging asm-code-lens with breakpoints](https://user-images.githubusercontent.com/16851802/208610029-c45a8f51-b1d7-46ca-9215-2fe4b112052e.png)

You may try install [esbuild Problem Matchers](https://marketplace.visualstudio.com/items?itemName=connor4312.esbuild-problem-matchers) if not yet.

**Comment by maziac** [comment]
Why do you think a problem matcher will help here?

**Comment by Crystal-RainSlide** [comment]
It's just, that problem matcher is the only common thing may be installed only on my side but not yours... I 

- Breakpoint on both `.ts` files and `extension.js` works for me;
- Mocha test still need to build without bundler and write js files to out/src & out/tests, but it's not causing problem for me;
- I didn't touch VSCode Settings - Features - Debugging ...

**Comment by maziac** [comment]
A restart of  vscode did the trick.
I can now break in ts files.

However it is still not working as expected.
I set a breakpoint in the HoverProvider:
![Bildschirmfoto 2022-12-20 um 10 52 00](https://user-images.githubusercontent.com/3081973/208637252-c85ea9cf-6d98-4e8b-92c3-a9d1c5121b5c.jpg)
then I step-into 'getCompleteLabel' and get this:
![Bildschirmfoto 2022-12-20 um 10 52 57](https://user-images.githubusercontent.com/3081973/208637471-1c439637-9931-47c4-8ab9-98144611c6cb.jpg)

Afterwards I cannot press the debug buttons anymore, only terminate (the red square) does work after about half a minute.

It seems to be related to the function 'getCompleteLabel'. Another function, e.g. 'Config.getConfigForDoc' does work without problem.
Do you experience a similar behavior?

**Comment by Crystal-RainSlide** [comment]
No, I can step out after step in that function in `HoverProvider.ts` with no problem.

I'm hovering on some regular `.S` assembly, nothing special other than some `#include`s and `#define`s.

**Comment by maziac** [comment]
So, you can step into getCompleteLabel in grepextra.ts?
That is strange. What OS are you on? I'm on macOS.
Any ideas what could be special about grepextra.ts?

**Comment by maziac** [comment]
I restarted now the complete OS. 
Again the behavior got better.
Still I get extensionHost.js when stepping into getCompleteLabel, but I can now further step into it.
I.e. after about 3 stepIntos I reach the sources of getCompleteLabel.

I remember that I have enabled some setting in vscode years ago about stepping over internal code, but I can't remember what is was exactly.

**Comment by maziac** [comment]
OK, I managed to change the launch.json a bit and added:
~~~json

            "skipFiles": [
                "**/extensionHostProcess.js"
            ]
~~~

Now, on step-into, it skips extensionHostProcess.js and directly enters getCompleteLabel.

Is there maybe some global setting that you have set?

**Comment by maziac** [comment]
For the unit tests. I run them normally from the vscode UI. In order that I don't have to build them before running I would need to start the 'compile-nobundle'  watch script as well.
Or is there a better way to do it?
I'm also open to use something different then mocha.

**Comment by maziac** [comment]
Another question:
The esbuild problemMatcher seems to do nothing. The format is not recognized.
Is there a special config parameter for esbuild so that is creates the required format?

**Comment by Crystal-RainSlide** [comment]
> OK, I managed to change the launch.json a bit and added:
> 
> ```json
>             "skipFiles": [
>                 "**/extensionHostProcess.js"
>             ]
> ```
> 
> Now, on step-into, it skips extensionHostProcess.js and directly enters getCompleteLabel.
> 
> Is there maybe some global setting that you have set?

No! I got the same `extensionHostProcess.js` thing as I previously mentioned.

I only use debugging passively (or mainly for easier inspections), and I don't even know I can step though `extensionHostProcess.js`! 😄

> For the unit tests. I run them normally from the vscode UI. In order that I don't have to build them before running I would need to start the 'compile-nobundle' watch script as well. Or is there a better way to do it? I'm also open to use something different then mocha.

- Stay with mocha: https://github.com/RTVision/mocha-esbuild
- Goodbye mocha: I don't know, there are things that, I'm not familiar with, seems works fine. Like Jest with `esbuild-jest`.

> Another question: The esbuild problemMatcher seems to do nothing. The format is not recognized. Is there a special config parameter for esbuild so that is creates the required format?

I think it just needs an update. repo: https://github.com/connor4312/esbuild-problem-matchers

**Comment by maziac** [comment]
Quick question: what command you used to compress the icon?
I would like to use it on other projects as well. :-)

**Comment by Crystal-RainSlide** [comment]
> Quick question: what command you used to compress the icon? I would like to use it on other projects as well. :-)

OptiPNG.

Actually, it's not just about the tools, it's also about the strategy. If we only look at the tools, for PNG, most of the tools, like OptiPNG, oxipng etc, they all do lossless compression, other than pngquant, which can do a kind of lossy compression that adds noise. That's it. One may find most of the tools he may need those days from [imagemin (sadly, unmaintained)'s repos](https://github.com/orgs/imagemin/repositories) or [Ultra7z Optimizers](https://supercompression.org/).

However, if we get strategy into the play, there are much more.

- You may reduce the pixels to 256x256, create an `icon-256.png` for the `local` dir, and move `icon.png` to the `remote` dir.
- Since 256 colors will do the 95~99% of `icon.png`, one may reduce its size by reduce its color from full RGB to 8 bit / 256 colors with [palette-based PNG](http://www.libpng.org/pub/png/book/chapter08.html#png.ch08.div.5.1), lossy, but no visual difference.
  - I mainly use [Paint.NET](https://getpaint.net/) and [OptiPNG plugin](https://forums.getpaint.net/topic/114190-optipng-filetype-2019-05-07/) for this:
    - The only command line lossy PNG color reducion tool I know is [`pngnq`](https://sourceforge.net/projects/pngnq/)/[`pngnq-s9`](https://sourceforge.net/projects/pngnqs9/), and they are too old, their output really requires another run from OptiPNG etc.
    - For lossless-ness, other tools only do lossless PNG color reduction, they only reduces the color when there are 256 or less colors in that PNG file.
    - pngquant isn't doing this kind of lossy compression.
- pngquant's lossy compression works best on "complex" images, the ones that most people would just save them to JPG to shink their size.
- Looking further, we already got WebP. We'll have [JPEG XL](https://jpegxl.info/) if Google don't manage to murder & replace it with their WebP2.
- Use SVG when possible.
- ...

So:
- Use SVG when possible
- use new image formats when possible
- Reduce pixels and colors when it's fine to do so
- Use those command line tools
- Use your imagination

**Comment by maziac** [comment]
Did you use any special command line options?

**Comment by Crystal-RainSlide** [comment]
I generally use a higher compression level/optimization level, enable metadata stripping if it's not enabled by default, and use `-Z` (`--zopfli`) for oxipng.

**Comment by maziac** [comment]
One other question: I just ran into a problem with esbuild and googling does not help either.
It seems that esbuild does not show any error or warning if a function is missing.
E.g. in asm-code-lens remove the function getConfigForDoc in config.ts and then run the rpm script esbuild-node.
It compiles without problems. Why?

When I put a breakpoint in and debug (e.g. provideCodeLenses) the call to getConfigForDoc fails but doesn't even  show up as error in the console.

How can I make esbuild report an error?

**Comment by Crystal-RainSlide** [comment]
For its _performance_ and everything, esbuild only reports parsing errors or serious problems just like parsing errors, it isn't doing any checking: https://esbuild.github.io/content-types/#typescript

Also see all those caveats on that page.

I'm using eslint which has extension support for auto-linting on open file(s), I think TypeScript/tsc has that from VSCode's built-in TypeScript support too? After `getConfigForDoc` got removed, I got error(s) when opening files that calls `getConfigForDoc`.

But, any way, you may use `--noEmit` with `tsc -p ./` or `tsc -w -p ./` along with the `$tsc` problemMatcher, to let `tsc` check for problems. I have a similar `lint` task for this, in case I need to check all the problems that eslint got, even for the files that I'm not currently working on.

**Comment by maziac** [comment]
Thanks for the Info.
I will use that --noemit option.
