### ISSUE TITLE
not work references

### ISSUE THREAD

**Issue by DeadlyKom** [maziac/asm-code-lens#91]
- reference counter not showing up
![image](https://user-images.githubusercontent.com/23453697/209072963-b70f8ede-9739-41da-b71e-786695f4e478.png)
- fast transition stopped working Ctrl + mouse click on the label
- there is also no description when hovering over a label/constant

**Comment by maziac** [comment]
Can you zip your project and attach it here?

Is it a multiroot project?

**Comment by DeadlyKom** [comment]
https://github.com/DeadlyKom/TSLib

**Comment by maziac** [comment]
Is it ASM Code Lens version 2.2?

**Comment by maziac** [comment]
I can't find any sources with the text "ConnectInput" inside the TSLib GitHub repo.

TSLib itself has references:
![Bildschirmfoto 2022-12-22 um 11 42 10](https://user-images.githubusercontent.com/3081973/209117073-725d25c2-5510-4409-a11a-4af7e9ba390c.jpg)

I have used:
![Bildschirmfoto 2022-12-22 um 11 42 44](https://user-images.githubusercontent.com/3081973/209117189-120cfe98-d9f0-4775-8ff3-d27ebed44076.jpg)

Do you have a multiroot setup (several workspace folders combined into one workspace)?

**Comment by DeadlyKom** [comment]
![image](https://user-images.githubusercontent.com/23453697/209125460-28a1f666-7502-41ae-b93a-9929c9cc000a.png)

**Comment by DeadlyKom** [comment]
> I can't find any sources with the text "ConnectInput" inside the TSLib GitHub repo.

This is the "Net" branch, I pushed it to the master branch

**Comment by DeadlyKom** [comment]
> TSLib itself has references:

this is very strange, something broke for me (

**Comment by maziac** [comment]
Here from Net branch:
![Bildschirmfoto 2022-12-22 um 12 53 32](https://user-images.githubusercontent.com/3081973/209128962-64d5c25d-2f06-43a1-b5dd-42d974225096.jpg)

Have you maybe turned off references in the settings, e.g in folder, workspace or user?

**Comment by DeadlyKom** [comment]
> Have you maybe turned off references in the settings, e.g in folder, workspace or user?
![image](https://user-images.githubusercontent.com/23453697/209134190-7fe87d16-d999-45d8-a07b-5314f914254a.png)
![image](https://user-images.githubusercontent.com/23453697/209134269-f2acca78-41c2-427d-af79-a6516187b1e0.png)

**Comment by maziac** [comment]
So, everything fine there.

I guess you already tried to toggle the "Enable Code Lens" setting and restarted vscode...

**Comment by DeadlyKom** [comment]
yes, but still not working

**Comment by maziac** [comment]
I'm running out of ideas.

Could you downgrade to 2.1.0 to check if it is still working there.

**Comment by DeadlyKom** [comment]
disable extension Z80 Macro Assembler and working
https://marketplace.visualstudio.com/items?itemName=mborik.z80-macroasm

**Comment by maziac** [comment]
Ah, OK.

Yes, maybe I should make a note in the readme.
Both extensions nearly do the same. 
It's probably better to install only one of them.

Anyhow, I think the underlying problem has to do with the file associations.
Probably the files were not associated to "Assembler file" (the one from asm-code-lens) or the file extension of both extensions simply clash.

Good to hear that it is working now.

**Comment by DeadlyKom** [comment]
![image](https://user-images.githubusercontent.com/23453697/209154770-8888529b-8197-4ccc-96d8-a90659278950.png)
there is such a function, it is very convenient as for me

**Comment by DeadlyKom** [comment]
I also noticed that either not always, or at all, jumping by name and searching for links does not work when the name of the tags is so long
Example, the first and second are the same function, only the first one is declared correctly, and the second one is not.
![image](https://user-images.githubusercontent.com/23453697/209156497-02f0bdc8-7798-42a8-abe5-7222dad9f0dc.png)
and
![image](https://user-images.githubusercontent.com/23453697/209156549-809c6ac3-6f96-406b-8ad0-6c7d52b1cbae.png)

**Comment by maziac** [comment]
I think the problem is described in [Known Issues](https://github.com/maziac/asm-code-lens#known-issues):
>This extension doesn't use a structured approach but just looks at all asm files without hierarchy. This means that sjasmplus MODULE definitions are only taken into account if they are used within the same file.

I.e.  if you use MODULE and then include a file the labels in the file are interpreted without the MODULE prefix.

**Comment by maziac** [comment]
> ![image](https://user-images.githubusercontent.com/23453697/209154770-8888529b-8197-4ccc-96d8-a90659278950.png)
> there is such a function, it is very convenient as for me

So, can't you switch to the "Z80 Macro-Assembler"? AFAIK it supports also code lenses.

**Comment by DeadlyKom** [comment]
> So, can't you switch to the "Z80 Macro-Assembler"? AFAIK it supports also code lenses.
configured through the VCode editor itself

> I.e. if you use MODULE and then include a file the labels in the file are interpreted without the MODULE prefix.
I use essentially global includes at the beginning, you can find a similar approach in the library link that I threw above

**Comment by maziac** [comment]
I have done some tests with z80-macroasm and I think I know now what is happening.

Most probably the file association was set to z80-macroasm for your assembly files.
If both, asm-code-lens and z80-macroasm, are installed both define a language id.
asm-code-lens: "Assembler file"
z80-macroasm: "Z80 Macro Assembler"
You can see it at the bottom right in the status bar, e.g. select a asm file and check:
![Bildschirmfoto 2022-12-23 um 12 27 40](https://user-images.githubusercontent.com/3081973/209328441-3784ac82-950f-4611-b159-53d9c936e455.jpg)

Code lenses in asm-code-lens do work only if the association is set to "Assembler file", see here:
![fileassoc](https://user-images.githubusercontent.com/3081973/209328922-2598f99c-49e8-40e4-afe7-a2717270035e.gif)
(BTW I was wrong assuming that Z80 Macro Assembler does code lenses, it does not.)

For your rulers problem. It is a generic feature of vscode, i.e. not z80-macroasm specific.
I.e. in your settings above simply exchange "[z80-macroasm]" with "[asm-collection]" (the internal name of the language id defined by asm-code-lens) and it will work. (At least on all files that are set to language id "Assembler file".
![Bildschirmfoto 2022-12-23 um 12 40 09](https://user-images.githubusercontent.com/3081973/209330227-232e7fd0-659d-4340-976a-6be0a9e13014.jpg)

**Comment by DeadlyKom** [comment]
oh thanks you did a great job, i really appreciate it

**Comment by maziac** [comment]
You are welcome.
