### ISSUE TITLE
[Feature] Add support for code formating 

### ISSUE THREAD

**Issue by awh6al** [maziac/asm-code-lens#95]
I'm using [https://github.com/yamnikov-oleg/nasmfmt](url). It's very useful to add some method to at least allow such feature
 AKA: `format on save`

**Comment by maziac** [comment]
So, what is the problem.
Simply use that project to format your code.

**Comment by awh6al** [comment]
I just ask how to set `path/to/bin` option to trigger such tool when  i press `Ctrl+s` ??

**Comment by maziac** [comment]
You have to look for vscode features.
I.e. you can do so by yourself.
E.g. have a look here https://dae.me/blog/2603/vs-code-bind-one-key-to-multiple-commands-without-an-extension/

**Comment by awh6al** [comment]
That's it, thanks @maziac for your time.
