### ISSUE TITLE
Reference information is always zero

### ISSUE THREAD

**Issue by luc0x61** [maziac/asm-code-lens#97]
I don't know if anything's wrong, but I can't see any reference count to actual code, in many tens of thousands of lines of code I'm revising.
Every label always shows a count of **zero**, as shown in the picture, where a couple of them are closely placed to the shown jumps (the same happens with calls too)
![2023-01-26 08_56_36-ASMlens - Visual Studio Code](https://user-images.githubusercontent.com/56227954/214785627-f0e46f61-af68-491e-97c9-a6d84ff3b5db.png)

Note that labels are correctly recognized also in the outline.

**Comment by maziac** [comment]
Could you please attach here your project (or part of the project) so I could reproduce the problem.
And please also copy a screenshot of your asm-code-lens settings.

**Comment by maziac** [comment]
No response.

**Comment by dah33** [comment]
@maziac I have the same issue.

![image](https://github.com/user-attachments/assets/05135b6d-77fa-44e1-ad75-ed95f328330b)

```
  ORG 32768
  JP BEGIN

BEGIN:
  NOP
```

This is latest VS Code running on Linux Mint:
```
Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 5.15.0-122-generic
```

I have disabled all extensions apart from ASM Code Lens. There is nothing in the Output tab.

**Comment by maziac** [comment]
Just tested your code, seems to work fine with me (asm-code-lens v2.6.1, vscode Version: 1.93.1).

![Bildschirmfoto 2024-10-05 um 16 11 45](https://github.com/user-attachments/assets/427265bd-69a2-4e5e-b45c-76d22e64ffe5)
![Bildschirmfoto 2024-10-05 um 16 12 05](https://github.com/user-attachments/assets/10467cbe-3722-4e6c-a3d0-b90001b744f6)

Maybe there is something else with your code. 

Can you copy your settings/preferences for asm-code-lens.
What a bout the file extension, is it correct (e.g. *.asm), is it recognized as assembler file:
Do you see
![Bildschirmfoto 2024-10-05 um 16 17 59](https://github.com/user-attachments/assets/8efd7f37-9ac2-4064-8331-58d171fa3a1e)
in the bottom status line if you select  the file?

**Comment by dah33** [comment]
Thank you for the quick answer! It all looks right to me:

![image](https://github.com/user-attachments/assets/056a302d-72f2-4a88-b021-0fcf80d81bcd)

VS Code is v1.94.0 (so a minor bump from yours) and asm-code-lens is v2.6.1, other versions here:

```
Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 5.15.0-122-generic
```

Interestingly, Find All References shows "No results." and Go To Definition says "No definition found for 'BEGIN'" but "Go To References" brings up the inline viewer:

![image](https://github.com/user-attachments/assets/d1276a95-1f3d-491e-a520-c8f6b2524534)

![image](https://github.com/user-attachments/assets/92507eb5-e7c7-4d7f-98d7-0f9de9a94d8b)

**Comment by maziac** [comment]
Strange.
Did you check the vscode debug console for any suspicious output originated from asm-code-lens?

Do you have other files in the same folder? Maybe asm-code-lens is crashing on some other file when it collects all references.

Could you try to put your file in a new folder (as the only file) and open a new instance of vscode on that folder.

**Comment by dah33** [comment]
I've tried a new folder with just this file, and all other extensions turned off, still the same issue.

It does seem to be intermittent, as when I opened VSCode this morning, I saw "1 reference" but when I ctrl-clicked on "BEGIN" it reset to "0 references". 

There's nothing in the debug or problems consoles--is there a debug toggle for the extension? I've tried launching with `code --log maziac.asm-code-lens:debug .` but it doesn't generate any output.

**Comment by dah33** [comment]
Update: I commented out ALL my User `settings.json` and it is magically started working (after a restart)! I added them all back and, erm, it's still working (after another restart). Then I opened a larger project, a 1000+ line disassembly, and scrolled around for a while and could see the ref counts, but then when I right click "Go to References", it breaks:

![image](https://github.com/user-attachments/assets/7e1fe5a5-cc45-4dc4-af9c-0bcff2a7ac60)

![image](https://github.com/user-attachments/assets/e483f67d-2db3-4709-9078-c821a8883275)

**Comment by maziac** [comment]
(I now updated to  vscode 1.94.0. I still do not see your problem.)

The problem with the 1000+ line disassembly: does it also appear if you comment all your user settings.json?
Maybe it is a setting but does not happen right from the beginning.

Could you please also check to just comment your asm-code-lens settings.
